// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotSecDotNet.Data;

#nullable disable

namespace NotSecDotNet.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20230329125517_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("NotSecDotNet.Model.MovieObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MovieObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A beautiful, handpainted lively model of the young Lea.",
                            Name = "Princess Lea figure",
                            Price = 3500
                        },
                        new
                        {
                            Id = 2,
                            Description = "A beautiful, handpainted exclusvely-green model of Yoda.",
                            Name = "Yoda figure",
                            Price = 3600
                        },
                        new
                        {
                            Id = 3,
                            Description = "A full-sized authentic costume of Darth-veder with boots, trousers, robe, mask and a beutifully cracted light-sword",
                            Name = "Full Darth Veder Armor",
                            Price = 214750
                        });
                });

            modelBuilder.Entity("NotSecDotNet.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebPageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "youda@jeditemple.org",
                            Motto = "I don't know how old I am",
                            Name = "Yoda",
                            Password = "NoSecretsATrueJediHas",
                            Sex = "m",
                            WebPageUrl = "http://www.starwars.com/databank/yoda"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "vader@jeditemple.org",
                            Motto = "I see a red door and I want it paint it back",
                            Name = "Darth Vader",
                            Password = "IamYourFather",
                            Sex = "m",
                            WebPageUrl = "http://www.starwars.com/databank/vader"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "leia@jeditemple.org",
                            Motto = "I wish I have choosen the Wookie instead",
                            Name = "Princess Leia",
                            Password = "Hansword123",
                            Sex = "f",
                            WebPageUrl = "http://www.starwars.com/databank/leia"
                        });
                });

            modelBuilder.Entity("NotSecDotNet.model.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
                            Genre = "sci-fi",
                            Title = "Star Wars - A new hope"
                        },
                        new
                        {
                            Id = 2,
                            Description = "After the Rebels are overpowered by the Empire, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
                            Genre = "sci-fi",
                            Title = "Star Wars - The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 3,
                            Description = "After rescuing Han Solo from Jabba the Hutt, the Rebels attempt to destroy the second Death Star, while Luke struggles to help Darth Vader back from the dark side.",
                            Genre = "sci-fi",
                            Title = "Star Wars - The Return of the Jedi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
